//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fragor
    {
        public int ID { get; set; }
        public string Fraga { get; set; }
        public string SvarA { get; set; }
        public string SvarB { get; set; }
        public string SvarC { get; set; }
        public string SvarD { get; set; }
        public string RattSvar { get; set; }
    }
}
